site_name: HRC Tech Docs
site_url: https://hrc-pme.github.io/hrc-tech-docs/
use_directory_urls: true

repo_url: https://github.com/hrc-pme/hrc-tech-docs.git
repo_name: hrc-pme/hrc-tech-docs

theme:
  name: material
  language: zh-TW
  font:
    text: Huninn
  icon:
    repo: octicons/git-merge-16

  features:
    # - announce.dismiss              # 可關閉的公告欄（搭配 extra.announcement 使用）
    - content.action.edit           # 顯示「編輯本頁」按鈕
    - content.action.view           # 顯示「檢視原始檔」按鈕
    - content.code.annotate         # 支援程式碼行註解（需配合特定語法）
    - content.code.copy             # 程式碼區塊右上角顯示「複製」按鈕
    # - content.code.select           # 點擊即可選取整段程式碼（非複製）
    - content.footnote.tooltips     # 鼠標懸停於腳註，顯示提示泡泡
    - content.tabs.link             # 支援連結到特定 tab（分頁內容）
    - content.tooltips              # 顯示文字提示（使用 <abbr> 語法）

    # - header.autohide               # 捲動時自動隱藏上方導覽列
    - header.tabs.sticky            # 將頂部導覽列固定在頁面頂部
    - header.tabs.sticky.scrollable # 導覽列可捲動，適用於長導覽列

    - navigation.expand             # 預設展開所有側邊欄層級
    - navigation.footer             # 顯示「上一頁／下一頁」頁腳導覽
    - navigation.indexes            # 支援資料夾內的 index.md 成為目錄首頁
    - navigation.instant            # 啟用即時頁面切換（無需整頁重載）
    - navigation.instant.prefetch   # 預先載入連結頁面，提升速度
    - navigation.instant.progress   # 即時切換時顯示進度條
    - navigation.prune              # 隱藏未列入 nav 的頁面（靜態生成仍存在）
    - navigation.sections           # 分區顯示 nav 區塊（提升閱讀層次）
    - navigation.tabs               # 將頂部導覽列設為分頁樣式
    - navigation.tabs.sticky        # 將導覽分頁固定在頁面頂部
    - navigation.top                # 顯示「回到頂端」按鈕
    - navigation.tracking           # 側邊欄高亮當前閱讀小節
    - navigation.tracking.scrollable # 側邊欄可捲動，適用於長頁面

    - search.highlight              # 搜尋結果自動高亮顯示
    - search.share                  # 搜尋列加入「分享搜尋結果」按鈕
    # - search.suggest                # 輸入搜尋文字時提供建議補全

    - toc.follow                    # 目錄 (TOC) 跟隨捲動時高亮顯示
    # - toc.integrate                 # 將目錄整合進側邊欄中（非右側浮動 TOC）


  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

nav:
  - Home: index.md

  - O-Week: 
    - oweek/index.md
    - 1.Linux: oweek/1.linux.md
    - 2.SSH: oweek/2.ssh.md
    - 3.Git: oweek/3.git.md
    - 4.Docker: oweek/4.docker.md
    - 5.ROS2: oweek/5.ros2.md

  - Conventions: 
    - conventions/index.md
    - 1.commit: conventions/1.commit.md
    - 2.gitignore: conventions/2.gitignore.md
    - 3.repo.md: conventions/3.repo.md

  - Robot: 
    - robot/index.md
    - Koch-Robot-Arm-V1.1: robot/koch.md
    - Interbotix-ViperX300s: robot/viperX300s.md
    - Stretch-3: robot/stretch3.md
    - LoCoBot: robot/locobot.md
  
  - Contribution Guide: contribution.md

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.magiclink
  - toc:
      permalink: true
  
plugins:
  - include-markdown

extra_css:
  - stylesheets/extra.css