# ros2_tutorial/mkdocs.yml
site_name: O-Week
site_url: https://hrc-pme.github.io/O-Week/
use_directory_urls: false

theme:
  name: material
  
nav:
  - Homepage: index.md

  - tutorials:
    - 1.Linux: tutorials/1-linux.md
    - 2.SSH: tutorials/2-ssh.md
    - 3.Git: tutorials/3-git.md
    - 4.Docker: tutorials/4-docker.md
    - 5.ROS2: tutorials/5-ros2.md