site_name: HRC Tech Docs
site_url: https://hrc-pme.github.io/hrc-tech-docs/
use_directory_urls: true

repo_url: https://hrc-pme.github.io/hrc-tech-docs/
repo_name: hrc-pme/hrc-tech-docs

theme:
  name: material
  language: zh-TW
  font:
    text: Huninn
  icon:
    repo: octicons/git-merge-16

  features:
    - navigation.tabs            # Top horizontal navigation
    - navigation.sections        # Show groups (second level) on the left
    - navigation.expand          # Groups expanded by default on the left
    - toc.integrate              # Show section TOC on the left instead of the right

  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

  
nav:
  - Home: index.md

  - O-Week:
    - oweek/intro.md
    - 1.Linux: oweek/1.linux.md
    - 2.SSH: oweek/2.ssh.md
    - 3.Git: oweek/3.git.md
    - 4.Docker: oweek/4.docker.md
    - 5.ROS2: oweek/5.ros2.md

  - Conventions:
    - conventions/intro.md
    - 1.commit: conventions/1.commit.md
    - 2.repo: conventions/2.repo.md

  - Robot:
    - robot/intro.md
    - Koch-Robot-Arm-V1.1: robot/koch.md
    - Interbotix-ViperX300s: robot/viperX300s.md
    - Stretch-3: robot/stretch3.md
    - LoCoBot: robot/locobot.md
  
  - Contribution: contribution.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.magiclink
  - toc:
      permalink: true