# ros2_tutorial/mkdocs.yml
site_name: O-Week
theme:
  name: material
  
nav:
  - Homepage: homepage.md

  - tutorials:
    - Linux: tutorials/1-linux.md
    - SSH: tutorials/2-ssh.md
    - Git: tutorials/3-git.md
    - Docker: tutorials/4-docker.md
    - ROS2: tutorials/5-ros2.md

theme:
  name: material