services:
  mkdocs:
    build:
      context: .  
      dockerfile: Dockerfile
    image: hrcnthu/mkdocs:default
    ports:
      - "8000:8000"
    volumes:
      - ../:/docs
    stdin_open: true
    tty: true